%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Custom Parameters
#--------------------------------------------------------------------------------------------

# CLAHE
# clip_limit: 3 #3 - 4 ish
# grid_size: 4 # 4 - 20, heavy diminishing returns after 10 ish

# Pressure sensor noise
# something

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 543.3327734182214
Camera1.fy: 542.398772982566
Camera1.cx: 489.02536042247897
Camera1.cy: 305.38727712002805

Camera1.k1: -0.1255945656257394
Camera1.k2: 0.053221287232781606
Camera1.p1: 9.94070021080493e-05
Camera1.p2: 9.550660927242349e-05

Camera.width: 968
Camera.height: 608

# Camera frames per second 
Camera.fps: 20

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ -0.99937221, -0.03437489, -0.00857581, -0.01928963,
           0.00901561, -0.01265975, -0.99987922, -0.17514254,
           0.03426217, -0.99932882,  0.01296171, -0.0267952,
           0.0,   0.0,  0.0,  1.0]
#    data: [  0.0,   0.0,  1.0,  0.0,
#            -1.0,   0.0,  0.0,  0.0,
#             0.0,  -1.0,  0.0,  0.0,
#             0.0,   0.0,  0.0,  1.0]
# Insert KFs when recently lost
# IMU.InsertKFsWhenLost: 0

# IMU noise
IMU.NoiseGyro: 0.003
IMU.NoiseAcc: 0.05
IMU.GyroWalk: 0.0001
IMU.AccWalk: 0.0015
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

