%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Custom Parameters
#--------------------------------------------------------------------------------------------

# CLAHE
# clip_limit: 3 #3 - 4 ish
# grid_size: 4 # 4 - 20, heavy diminishing returns after 10 ish

# Pressure sensor noise
# something

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 958.245993
Camera1.fy: 950.440316
Camera1.cx: 972.664699
Camera1.cy: 512.687404

Camera1.k1: -0.212992
Camera1.k2: 0.041363
Camera1.p1: -0.000334
Camera1.p2: -0.000479

Camera.width: 1920
Camera.height: 1080

Camera.newWidth: 600
Camera.newHeight: 350

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [  0.0,   0.0,  1.0,  0.0,
            1.0,   0.0,  0.0,  0.0,
            0.0,   1.0,  0.0,  0.2,
            0.0,   0.0,  0.0,  1.0]
   # data: [  0.0,   0.0,  1.0,  0.3566,
   #          1.0,   0.0,  0.0,  0.008,
   #          0.0,   1.0,  0.0, -0.23,
   #          0.0,   0.0,  0.0,  1.0]
#    data: [  0.0,   0.0,  1.0,  0.0,
#            -1.0,   0.0,  0.0,  0.0,
#             0.0,  -1.0,  0.0,  0.0,
#             0.0,   0.0,  0.0,  1.0]
# Insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise
IMU.NoiseGyro: 0.0003394
IMU.NoiseAcc: 0.004
IMU.GyroWalk: 0.000038785 
IMU.AccWalk: 0.006
IMU.Frequency: 100.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

